#!/usr/bin/env node
// Build the branded documentation site from odoc output.
//
// Copies _build/default/_doc/_html to ./_site (dune marks its output read-only,
// so we never mutate it in place), then brands the copy:
//   - appends the Chatoyant overlay to odoc's stylesheet,
//   - adds a favicon and a branded footer backlink to every page,
//   - replaces the bare package-list landing with a branded hero.
// Run after `dune build @doc`; ./_site is what gets deployed to GitHub Pages.

import { existsSync } from "node:fs";
import { chmod, cp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "_build/default/_doc/_html");
const OUT = join(ROOT, "_site");
const CSS_SRC = join(ROOT, "doc/odoc-brand.css");
const LOGO_SRC = join(ROOT, "assets/chatoyant-logo.png");
const ODOC_CSS = join(OUT, "odoc.support/odoc.css");
const LOGO_DEST = join(OUT, "chatoyant-logo.png");
const INDEX = join(OUT, "index.html");

const FOOTER =
  '<footer class="chatoyant-footer">Made with <span class="heart">&#9829;</span> by ' +
  '<a href="https://anonyfox.com" target="_blank" rel="noopener">Anonyfox</a> &middot; ' +
  '<a href="https://github.com/Anonyfox/chatoyant" target="_blank" rel="noopener">GitHub</a>' +
  "</footer>";

const HERO =
  '<div class="chatoyant-hero">' +
  '<img class="chatoyant-hero-logo" src="chatoyant-logo.png" alt="Chatoyant logo"/>' +
  '<h1 class="chatoyant-hero-title">Chatoyant</h1>' +
  '<p class="chatoyant-hero-tagline">OCaml-first SDK for LLM providers — typed provider ' +
  "clients, structured outputs, tool calling, streaming, and token/cost accounting, with a " +
  "zero-dependency JavaScript package generated by Melange.</p>" +
  '<div class="chatoyant-hero-links">' +
  '<a href="chatoyant/index.html">API Reference</a>' +
  '<a href="https://github.com/Anonyfox/chatoyant">GitHub</a>' +
  '<a href="https://www.npmjs.com/package/chatoyant">npm</a>' +
  '<a href="https://opam.ocaml.org/packages/chatoyant/">opam</a>' +
  "</div></div>";

const DESCRIPTION =
  "OCaml-first SDK for LLM providers (OpenAI, Anthropic, xAI, OpenRouter, local) with " +
  "structured outputs, tool calling, streaming, and a zero-dependency Melange-generated " +
  "JavaScript package.";

if (!existsSync(SRC)) {
  console.error(`brand-docs: ${SRC} not found — run \`dune build @doc\` first`);
  process.exit(1);
}

await rm(OUT, { recursive: true, force: true });
await cp(SRC, OUT, { recursive: true });
await cp(LOGO_SRC, LOGO_DEST);

async function* walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) {
      await chmod(p, 0o755); // dune output is read-only; make the copy writable
      yield* walk(p);
    } else {
      yield p;
    }
  }
}

let count = 0;
for await (const file of walk(OUT)) {
  await chmod(file, 0o644);
  if (!file.endsWith(".html")) continue;

  let html = await readFile(file, "utf8");

  if (html.includes("</head>") && !html.includes('rel="icon"')) {
    const fav = relative(dirname(file), LOGO_DEST).split(sep).join("/");
    html = html.replace("</head>", `<link rel="icon" type="image/png" href="${fav}"/></head>`);
  }
  if (html.includes("</body>") && !html.includes("chatoyant-footer")) {
    html = html.replace("</body>", `${FOOTER}</body>`);
  }
  if (file === INDEX) {
    html = html
      .replace(
        "<title>index</title>",
        `<title>Chatoyant — OCaml-first LLM SDK</title>\n    <meta name="description" content="${DESCRIPTION}"/>`,
      )
      .replace("<h2>OCaml package documentation</h2>", HERO);
  }

  await writeFile(file, html);
  count += 1;
}

const brand = await readFile(CSS_SRC, "utf8");
const css = await readFile(ODOC_CSS, "utf8");
await writeFile(ODOC_CSS, `${css}\n/* chatoyant-brand */\n${brand}`);

console.log(`brand-docs: built ${OUT} (${count} pages branded)`);
